<?php
require_once('../config.php');

session_start();

// Check if the user is not logged in
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    // User is not logged in, redirect them to the login page
    header('Location: ' . LOGIN . '/login.php');
    exit();
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Turn on autocommit to start a new transaction
    $conn->autocommit(FALSE);

    $name = htmlspecialchars($_POST['name'], ENT_QUOTES, 'UTF-8');
    $overview = htmlspecialchars($_POST['overview'], ENT_QUOTES, 'UTF-8');
    $keyFacts = htmlspecialchars($_POST['key_facts'], ENT_QUOTES, 'UTF-8');
    $highlights = htmlspecialchars($_POST['highlights'], ENT_QUOTES, 'UTF-8');
    $imageUrl = filter_var($_POST['image_url'], FILTER_VALIDATE_URL) ? $_POST['image_url'] : false;

    if (!$name || !$overview || !$keyFacts || !$highlights || !$imageUrl) {
        // One or more inputs are empty or not valid. Handle this error.
    }

    // Insert data into the csym_courses table
    $stmt = $conn->prepare("INSERT INTO csym_courses (name, overview, key_facts, highlights, image_url) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param('sssss', $name, $overview, $keyFacts, $highlights, $imageUrl);
    $stmt->execute();

    // Get the autogenerated course_id
    $courseId = $conn->insert_id;

    // Prepare statement for csym_courses_content table
    $stmt = $conn->prepare("INSERT INTO csym_courses_content (course_id, tab_name, tab_content) VALUES (?, ?, ?)");
    $stmt->bind_param('iss', $courseId, $tabName, $tabContent);

    // Insert data into the csym_courses_content table
    $tabNames = array_map(function($tabName) {
        return htmlspecialchars($tabName, ENT_QUOTES, 'UTF-8');
    }, $_POST['tab_name'] ?? []);

    $tabContents = array_map(function($tabContent) {
        return htmlspecialchars($tabContent, ENT_QUOTES, 'UTF-8');
    }, $_POST['tab_content'] ?? []);

    foreach ($tabNames as $index => $tabName) {
        $tabContent = $tabContents[$index];
        $stmt->execute();
    }

    // If no errors occurred, commit the transaction
    if ($stmt->errno) {
        // An error occurred. Rollback changes.
        $conn->rollback();
        echo "Failed to insert data: (" . $stmt->errno . ") " . $stmt->error;
    } else {
        $conn->commit();
        header('Location: course_new.php');
        exit();
    }
}

include HTML . '/header.php'; ?>

<main>
    <h3>Δείγμα Έκθεσης Μαθήματος</h3>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <form name="add_name" id="add_name" action="course_new.php" method="POST">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" name="name" class="form-control" id="name">
                        </div>
                        <div class="form-group">
                            <label for="overview">Overview:</label>
                            <input type="text" name="overview" class="form-control" id="overview">
                        </div>
                        <div class="form-group">
                            <label for="key_facts">Key Facts:</label>
                            <input type="text" name="key_facts" class="form-control" id="key_facts">
                        </div>
                        <div class="form-group">
                            <label for="highlights">Highlights:</label>
                            <input type="text" name="highlights" class="form-control" id="highlights">
                        </div>
                        <div class="form-group">
                            <label for="image_url">Image URL:</label>
                            <input type="text" name="image_url" class="form-control" id="image_url">
                        </div>

                        <div class="form-group">
                            <label>Course Content:</label>
                            <div id="course_content">
                                <div class="content_row">
                                    <input type="text" name="tab_name[]" class="form-control" placeholder="Tab Name">
                                    <input type="text" name="tab_content[]" class="form-control" placeholder="Tab Content">
                                    <button type="button" class="btn btn-primary add_content_btn">Add More</button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script id="rendered-js">
        $(document).ready(function () {
            $(".add_content_btn").click(function () {
                var contentRow = '<div class="content_row">' +
                    '<input type="text" name="tab_name[]" class="form-control" placeholder="Tab Name">' +
                    '<input type="text" name="tab_content[]" class="form-control" placeholder="Tab Content">' +
                    '<button type="button" class="btn btn-primary remove_content_btn">Remove</button>' +
                    '</div>';
                $("#course_content").append(contentRow);
            });

            $(document).on('click', '.remove_content_btn', function () {
                $(this).closest('.content_row').remove();
            });
        });
    </script>
</main>
<?php include HTML . '/footer.php'; ?>
